

spring:
  application:
    name: ecommerce-api
    
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ecommerce_user
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  # CORS Configuration
  web:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "http://localhost:3001"
        - "http://localhost:4200"
        - "http://localhost:5173"
        - "http://localhost:8081"
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - PATCH
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
        
logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.web.cors: DEBUG
    
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    disable-swagger-default-url: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  
# Server configuration for better error handling
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# Management endpoints (optional - for health checks)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized